//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoStore.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviesGenre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoviesGenre()
        {
            this.Movies = new HashSet<Movie>();
            this.MoviesFormViewModels = new HashSet<MoviesFormViewModel>();
        }
    
        public byte Id { get; set; }
        public string Genre { get; set; }
        public Nullable<int> MoviesFormViewModel_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie> Movies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoviesFormViewModel> MoviesFormViewModels { get; set; }
        public virtual MoviesFormViewModel MoviesFormViewModel { get; set; }
    }
}
